// flow-typed signature: 98c6dec500d54f54790525ec0aa0ca65
// flow-typed version: <<STUB>>/snabbdom_v^0.7.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'snabbdom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'snabbdom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'snabbdom/dist/h' {
  declare module.exports: any;
}

declare module 'snabbdom/dist/h.min' {
  declare module.exports: any;
}

declare module 'snabbdom/dist/snabbdom-attributes' {
  declare module.exports: any;
}

declare module 'snabbdom/dist/snabbdom-attributes.min' {
  declare module.exports: any;
}

declare module 'snabbdom/dist/snabbdom-class' {
  declare module.exports: any;
}

declare module 'snabbdom/dist/snabbdom-class.min' {
  declare module.exports: any;
}

declare module 'snabbdom/dist/snabbdom-eventlisteners' {
  declare module.exports: any;
}

declare module 'snabbdom/dist/snabbdom-eventlisteners.min' {
  declare module.exports: any;
}

declare module 'snabbdom/dist/snabbdom-patch' {
  declare module.exports: any;
}

declare module 'snabbdom/dist/snabbdom-patch.min' {
  declare module.exports: any;
}

declare module 'snabbdom/dist/snabbdom-props' {
  declare module.exports: any;
}

declare module 'snabbdom/dist/snabbdom-props.min' {
  declare module.exports: any;
}

declare module 'snabbdom/dist/snabbdom-style' {
  declare module.exports: any;
}

declare module 'snabbdom/dist/snabbdom-style.min' {
  declare module.exports: any;
}

declare module 'snabbdom/dist/snabbdom' {
  declare module.exports: any;
}

declare module 'snabbdom/dist/snabbdom.min' {
  declare module.exports: any;
}

declare module 'snabbdom/dist/tovnode' {
  declare module.exports: any;
}

declare module 'snabbdom/dist/tovnode.min' {
  declare module.exports: any;
}

declare module 'snabbdom/examples/carousel-svg/build' {
  declare module.exports: any;
}

declare module 'snabbdom/examples/carousel-svg/script' {
  declare module.exports: any;
}

declare module 'snabbdom/examples/hero/build' {
  declare module.exports: any;
}

declare module 'snabbdom/examples/hero/script' {
  declare module.exports: any;
}

declare module 'snabbdom/examples/reorder-animation/build' {
  declare module.exports: any;
}

declare module 'snabbdom/examples/reorder-animation/script' {
  declare module.exports: any;
}

declare module 'snabbdom/examples/svg/build' {
  declare module.exports: any;
}

declare module 'snabbdom/examples/svg/script' {
  declare module.exports: any;
}

declare module 'snabbdom/gulpfile' {
  declare module.exports: any;
}

declare module 'snabbdom/h' {
  declare module.exports: any;
}

declare module 'snabbdom/helpers/attachto' {
  declare module.exports: any;
}

declare module 'snabbdom/hooks' {
  declare module.exports: any;
}

declare module 'snabbdom/htmldomapi' {
  declare module.exports: any;
}

declare module 'snabbdom/is' {
  declare module.exports: any;
}

declare module 'snabbdom/modules/attributes' {
  declare module.exports: any;
}

declare module 'snabbdom/modules/class' {
  declare module.exports: any;
}

declare module 'snabbdom/modules/dataset' {
  declare module.exports: any;
}

declare module 'snabbdom/modules/eventlisteners' {
  declare module.exports: any;
}

declare module 'snabbdom/modules/hero' {
  declare module.exports: any;
}

declare module 'snabbdom/modules/module' {
  declare module.exports: any;
}

declare module 'snabbdom/modules/props' {
  declare module.exports: any;
}

declare module 'snabbdom/modules/style' {
  declare module.exports: any;
}

declare module 'snabbdom/snabbdom.bundle' {
  declare module.exports: any;
}

declare module 'snabbdom/snabbdom' {
  declare module.exports: any;
}

declare module 'snabbdom/thunk' {
  declare module.exports: any;
}

declare module 'snabbdom/tovnode' {
  declare module.exports: any;
}

declare module 'snabbdom/vnode' {
  declare module.exports: any;
}

// Filename aliases
declare module 'snabbdom/dist/h.js' {
  declare module.exports: $Exports<'snabbdom/dist/h'>;
}
declare module 'snabbdom/dist/h.min.js' {
  declare module.exports: $Exports<'snabbdom/dist/h.min'>;
}
declare module 'snabbdom/dist/snabbdom-attributes.js' {
  declare module.exports: $Exports<'snabbdom/dist/snabbdom-attributes'>;
}
declare module 'snabbdom/dist/snabbdom-attributes.min.js' {
  declare module.exports: $Exports<'snabbdom/dist/snabbdom-attributes.min'>;
}
declare module 'snabbdom/dist/snabbdom-class.js' {
  declare module.exports: $Exports<'snabbdom/dist/snabbdom-class'>;
}
declare module 'snabbdom/dist/snabbdom-class.min.js' {
  declare module.exports: $Exports<'snabbdom/dist/snabbdom-class.min'>;
}
declare module 'snabbdom/dist/snabbdom-eventlisteners.js' {
  declare module.exports: $Exports<'snabbdom/dist/snabbdom-eventlisteners'>;
}
declare module 'snabbdom/dist/snabbdom-eventlisteners.min.js' {
  declare module.exports: $Exports<'snabbdom/dist/snabbdom-eventlisteners.min'>;
}
declare module 'snabbdom/dist/snabbdom-patch.js' {
  declare module.exports: $Exports<'snabbdom/dist/snabbdom-patch'>;
}
declare module 'snabbdom/dist/snabbdom-patch.min.js' {
  declare module.exports: $Exports<'snabbdom/dist/snabbdom-patch.min'>;
}
declare module 'snabbdom/dist/snabbdom-props.js' {
  declare module.exports: $Exports<'snabbdom/dist/snabbdom-props'>;
}
declare module 'snabbdom/dist/snabbdom-props.min.js' {
  declare module.exports: $Exports<'snabbdom/dist/snabbdom-props.min'>;
}
declare module 'snabbdom/dist/snabbdom-style.js' {
  declare module.exports: $Exports<'snabbdom/dist/snabbdom-style'>;
}
declare module 'snabbdom/dist/snabbdom-style.min.js' {
  declare module.exports: $Exports<'snabbdom/dist/snabbdom-style.min'>;
}
declare module 'snabbdom/dist/snabbdom.js' {
  declare module.exports: $Exports<'snabbdom/dist/snabbdom'>;
}
declare module 'snabbdom/dist/snabbdom.min.js' {
  declare module.exports: $Exports<'snabbdom/dist/snabbdom.min'>;
}
declare module 'snabbdom/dist/tovnode.js' {
  declare module.exports: $Exports<'snabbdom/dist/tovnode'>;
}
declare module 'snabbdom/dist/tovnode.min.js' {
  declare module.exports: $Exports<'snabbdom/dist/tovnode.min'>;
}
declare module 'snabbdom/examples/carousel-svg/build.js' {
  declare module.exports: $Exports<'snabbdom/examples/carousel-svg/build'>;
}
declare module 'snabbdom/examples/carousel-svg/script.js' {
  declare module.exports: $Exports<'snabbdom/examples/carousel-svg/script'>;
}
declare module 'snabbdom/examples/hero/build.js' {
  declare module.exports: $Exports<'snabbdom/examples/hero/build'>;
}
declare module 'snabbdom/examples/hero/script.js' {
  declare module.exports: $Exports<'snabbdom/examples/hero/script'>;
}
declare module 'snabbdom/examples/reorder-animation/build.js' {
  declare module.exports: $Exports<'snabbdom/examples/reorder-animation/build'>;
}
declare module 'snabbdom/examples/reorder-animation/script.js' {
  declare module.exports: $Exports<'snabbdom/examples/reorder-animation/script'>;
}
declare module 'snabbdom/examples/svg/build.js' {
  declare module.exports: $Exports<'snabbdom/examples/svg/build'>;
}
declare module 'snabbdom/examples/svg/script.js' {
  declare module.exports: $Exports<'snabbdom/examples/svg/script'>;
}
declare module 'snabbdom/gulpfile.js' {
  declare module.exports: $Exports<'snabbdom/gulpfile'>;
}
declare module 'snabbdom/h.js' {
  declare module.exports: $Exports<'snabbdom/h'>;
}
declare module 'snabbdom/helpers/attachto.js' {
  declare module.exports: $Exports<'snabbdom/helpers/attachto'>;
}
declare module 'snabbdom/hooks.js' {
  declare module.exports: $Exports<'snabbdom/hooks'>;
}
declare module 'snabbdom/htmldomapi.js' {
  declare module.exports: $Exports<'snabbdom/htmldomapi'>;
}
declare module 'snabbdom/is.js' {
  declare module.exports: $Exports<'snabbdom/is'>;
}
declare module 'snabbdom/modules/attributes.js' {
  declare module.exports: $Exports<'snabbdom/modules/attributes'>;
}
declare module 'snabbdom/modules/class.js' {
  declare module.exports: $Exports<'snabbdom/modules/class'>;
}
declare module 'snabbdom/modules/dataset.js' {
  declare module.exports: $Exports<'snabbdom/modules/dataset'>;
}
declare module 'snabbdom/modules/eventlisteners.js' {
  declare module.exports: $Exports<'snabbdom/modules/eventlisteners'>;
}
declare module 'snabbdom/modules/hero.js' {
  declare module.exports: $Exports<'snabbdom/modules/hero'>;
}
declare module 'snabbdom/modules/module.js' {
  declare module.exports: $Exports<'snabbdom/modules/module'>;
}
declare module 'snabbdom/modules/props.js' {
  declare module.exports: $Exports<'snabbdom/modules/props'>;
}
declare module 'snabbdom/modules/style.js' {
  declare module.exports: $Exports<'snabbdom/modules/style'>;
}
declare module 'snabbdom/snabbdom.bundle.js' {
  declare module.exports: $Exports<'snabbdom/snabbdom.bundle'>;
}
declare module 'snabbdom/snabbdom.js' {
  declare module.exports: $Exports<'snabbdom/snabbdom'>;
}
declare module 'snabbdom/thunk.js' {
  declare module.exports: $Exports<'snabbdom/thunk'>;
}
declare module 'snabbdom/tovnode.js' {
  declare module.exports: $Exports<'snabbdom/tovnode'>;
}
declare module 'snabbdom/vnode.js' {
  declare module.exports: $Exports<'snabbdom/vnode'>;
}
