// flow-typed signature: cdfdd95045d3a72cf83daf00cf242820
// flow-typed version: <<STUB>>/snabbdom-jsx_v^0.4.2/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'snabbdom-jsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'snabbdom-jsx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'snabbdom-jsx/examples/counter/build' {
  declare module.exports: any;
}

declare module 'snabbdom-jsx/examples/counter/js/counter' {
  declare module.exports: any;
}

declare module 'snabbdom-jsx/examples/counter/js/counterList' {
  declare module.exports: any;
}

declare module 'snabbdom-jsx/examples/counter/js/main' {
  declare module.exports: any;
}

declare module 'snabbdom-jsx/examples/hello/build' {
  declare module.exports: any;
}

declare module 'snabbdom-jsx/examples/hello/main' {
  declare module.exports: any;
}

declare module 'snabbdom-jsx/examples/svg/build' {
  declare module.exports: any;
}

declare module 'snabbdom-jsx/examples/svg/main' {
  declare module.exports: any;
}

declare module 'snabbdom-jsx/examples/svg/svg' {
  declare module.exports: any;
}

declare module 'snabbdom-jsx/examples/todomvc/build' {
  declare module.exports: any;
}

declare module 'snabbdom-jsx/examples/todomvc/js/constants' {
  declare module.exports: any;
}

declare module 'snabbdom-jsx/examples/todomvc/js/helpers' {
  declare module.exports: any;
}

declare module 'snabbdom-jsx/examples/todomvc/js/main' {
  declare module.exports: any;
}

declare module 'snabbdom-jsx/examples/todomvc/js/task' {
  declare module.exports: any;
}

declare module 'snabbdom-jsx/examples/todomvc/js/todos' {
  declare module.exports: any;
}

declare module 'snabbdom-jsx/snabbdom-jsx' {
  declare module.exports: any;
}

declare module 'snabbdom-jsx/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'snabbdom-jsx/examples/counter/build.js' {
  declare module.exports: $Exports<'snabbdom-jsx/examples/counter/build'>;
}
declare module 'snabbdom-jsx/examples/counter/js/counter.js' {
  declare module.exports: $Exports<'snabbdom-jsx/examples/counter/js/counter'>;
}
declare module 'snabbdom-jsx/examples/counter/js/counterList.js' {
  declare module.exports: $Exports<'snabbdom-jsx/examples/counter/js/counterList'>;
}
declare module 'snabbdom-jsx/examples/counter/js/main.js' {
  declare module.exports: $Exports<'snabbdom-jsx/examples/counter/js/main'>;
}
declare module 'snabbdom-jsx/examples/hello/build.js' {
  declare module.exports: $Exports<'snabbdom-jsx/examples/hello/build'>;
}
declare module 'snabbdom-jsx/examples/hello/main.js' {
  declare module.exports: $Exports<'snabbdom-jsx/examples/hello/main'>;
}
declare module 'snabbdom-jsx/examples/svg/build.js' {
  declare module.exports: $Exports<'snabbdom-jsx/examples/svg/build'>;
}
declare module 'snabbdom-jsx/examples/svg/main.js' {
  declare module.exports: $Exports<'snabbdom-jsx/examples/svg/main'>;
}
declare module 'snabbdom-jsx/examples/svg/svg.js' {
  declare module.exports: $Exports<'snabbdom-jsx/examples/svg/svg'>;
}
declare module 'snabbdom-jsx/examples/todomvc/build.js' {
  declare module.exports: $Exports<'snabbdom-jsx/examples/todomvc/build'>;
}
declare module 'snabbdom-jsx/examples/todomvc/js/constants.js' {
  declare module.exports: $Exports<'snabbdom-jsx/examples/todomvc/js/constants'>;
}
declare module 'snabbdom-jsx/examples/todomvc/js/helpers.js' {
  declare module.exports: $Exports<'snabbdom-jsx/examples/todomvc/js/helpers'>;
}
declare module 'snabbdom-jsx/examples/todomvc/js/main.js' {
  declare module.exports: $Exports<'snabbdom-jsx/examples/todomvc/js/main'>;
}
declare module 'snabbdom-jsx/examples/todomvc/js/task.js' {
  declare module.exports: $Exports<'snabbdom-jsx/examples/todomvc/js/task'>;
}
declare module 'snabbdom-jsx/examples/todomvc/js/todos.js' {
  declare module.exports: $Exports<'snabbdom-jsx/examples/todomvc/js/todos'>;
}
declare module 'snabbdom-jsx/snabbdom-jsx.js' {
  declare module.exports: $Exports<'snabbdom-jsx/snabbdom-jsx'>;
}
declare module 'snabbdom-jsx/test.js' {
  declare module.exports: $Exports<'snabbdom-jsx/test'>;
}
